services:
  db:
    image: mysql:5.7
    command: --max_allowed_packet=256M
    # command: --default-authentication-plugin=mysql_native_password
    container_name: server_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - data_base:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: server_app
    #command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - db:
    #       condition: service_healthy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 128M
      MEMORY_LIMIT: 4096M
    restart: always
    ports:
      - 8082:80

volumes:
  data_base: