# Generated by Django 4.1.13 on 2024-05-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_servativ_tabcargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servativ',
        ),
        migrations.DeleteModel(
            name='Tabcargo',
        ),
    ]
